[package]
name = "WBlockGUI"
version = "0.1.0"
edition = "2018"

[dependencies]
wlambda   = { path = "../../wlambda" }
wblockdsp = { path = ".." }
tuix      = { path = "../../tuix" }
femtovg   = "0.2.5"
