[package]
name = "WBlockGUI"
version = "0.1.0"
edition = "2018"

[dependencies]
wlambda   = { git = "https://github.com/WeirdConstructor/WLambda.git" }
wblockdsp = { path = ".." }
tuix      = { git = "https://github.com/geom3trik/tuix.git" }
femtovg   = "0.2.5"
